-- phpMyAdmin SQL Dump
-- version 4.7.4
-- https://www.phpmyadmin.net/
--
-- Hôte : 127.0.0.1:3306
-- Généré le :  mer. 20 déc. 2017 à 01:08
-- Version du serveur :  5.7.19
-- Version de PHP :  7.1.9

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de données :  `dbadlenoir`
--

-- --------------------------------------------------------

--
-- Structure de la table `admins`
--

DROP TABLE IF EXISTS `admins`;
CREATE TABLE IF NOT EXISTS `admins` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `username` varchar(200) NOT NULL,
  `password` varchar(200) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=2 DEFAULT CHARSET=latin1;

--
-- Déchargement des données de la table `admins`
--

INSERT INTO `admins` (`id`, `username`, `password`) VALUES
(1, 'admin', 'c7ad44cbad762a5da0a452f9e854fdc1e0e7a52a38015f23f3eab1d80b931dd472634dfac71cd34ebc35d16ab7fb8a90c81f975113d6c7538dc69dd8de9077ec');

-- --------------------------------------------------------

--
-- Structure de la table `flux`
--

DROP TABLE IF EXISTS `flux`;
CREATE TABLE IF NOT EXISTS `flux` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(200) NOT NULL,
  `link` varchar(200) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `link` (`link`)
) ENGINE=MyISAM AUTO_INCREMENT=13 DEFAULT CHARSET=latin1;

--
-- Déchargement des données de la table `flux`
--

INSERT INTO `flux` (`id`, `name`, `link`) VALUES
(3, 'Engadget', 'https://www.engadget.com/rss.xml'),
(9, 'abcnews', 'http://abcnews.go.com/abcnews/worldnewsheadlines');

-- --------------------------------------------------------

--
-- Structure de la table `news`
--

DROP TABLE IF EXISTS `news`;
CREATE TABLE IF NOT EXISTS `news` (
  `title` varchar(200) NOT NULL,
  `description` varchar(1000) NOT NULL,
  `link` varchar(200) NOT NULL,
  `guid` varchar(200) NOT NULL,
  `pubdate` datetime NOT NULL,
  `category` varchar(1000) NOT NULL,
  PRIMARY KEY (`guid`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Déchargement des données de la table `news`
--

INSERT INTO `news` (`title`, `description`, `link`, `guid`, `pubdate`, `category`) VALUES
('WATCH:  David Muir discusses fake news with Jimmy Kimmel', 'World News Tonight Anchor David Muir on Feb. 15, 2017, tells Jimmy Kimmel if you underestimate the audience, you do so at your own peril.', 'http://abcnews.go.com/Entertainment/video/david-muir-discusses-fake-news-jimmy-kimmel-45549891', 'http://abcnews.go.com/Entertainment/video/david-muir-discusses-fake-news-jimmy-kimmel-45549891', '2017-02-17 01:17:21', 'Entertainment'),
('WATCH:  David Muir\'s full interview on \'Jimmy Kimmel Live\'', 'Jimmy Kimmel interviews \"World News Tonight\" Anchor David Muir on \"Jimmy Kimmel Live,\" Feb. 15. 2017.', 'http://abcnews.go.com/Entertainment/video/david-muirs-full-interview-jimmy-kimmel-live-45550323', 'http://abcnews.go.com/Entertainment/video/david-muirs-full-interview-jimmy-kimmel-live-45550323', '2017-02-17 01:42:32', 'Entertainment'),
('Iran-backed Houthis fire another missile at Saudi Arabia, officials say', 'It\'s the third missile the Saudis say they have intercepted in two months.', 'http://abcnews.go.com/International/iran-backed-houthis-fire-missile-saudi-arabia-officials/story?id=51880986', 'http://abcnews.go.com/International/iran-backed-houthis-fire-missile-saudi-arabia-officials/story?id=51880986', '2017-12-19 16:31:42', 'International'),
('Russia calls Trump\'s national security strategy \'imperialist\'', '&quot;We are engaged in a new era of competition,&quot; Trump said.', 'http://abcnews.go.com/International/russia-calls-trumps-national-security-strategy-imperialist/story?id=51882015', 'http://abcnews.go.com/International/russia-calls-trumps-national-security-strategy-imperialist/story?id=51882015', '2017-12-19 17:06:52', 'International'),
('Biden, Meghan McCain get emotional talking about her father\'s cancer diagnosis', 'The former vice president was interviewed on &quot;The View.&quot;', 'http://abcnews.go.com/Politics/biden-praises-doug-jones-alabama-upset-rejecting-trump/story?id=51764810', 'http://abcnews.go.com/Politics/biden-praises-doug-jones-alabama-upset-rejecting-trump/story?id=51764810', '2017-12-13 18:48:44', 'Politics'),
('President Trump: Construction of border wall will begin in months', 'President Trump speaks with ABC News anchor David Muir in his first one-on-one interview as commander in chief of the U.S.', 'http://abcnews.go.com/Politics/president-trump-tells-abc-news-david-muir-construction/story?id=45007943', 'http://abcnews.go.com/Politics/president-trump-tells-abc-news-david-muir-construction/story?id=45007943', '2017-02-13 14:47:25', 'Politics'),
('Sen. Gillibrand says she took Trump\'s \'do anything\' remark as sexual innuendo', '&quot;Well, certainly that\'s how I and many people read it.&quot;', 'http://abcnews.go.com/Politics/sen-kirsten-gillibrand-trump-sexual-innuendo-stifle-voice/story?id=51762607', 'http://abcnews.go.com/Politics/sen-kirsten-gillibrand-trump-sexual-innuendo-stifle-voice/story?id=51762607', '2017-12-13 17:04:18', 'Politics'),
('TRANSCRIPT: ABC News anchor David Muir interviews President Trump', 'This is a transcript of ABC News anchor David Muirâ€™s interview with President Trump on Jan. 25, 2017.', 'http://abcnews.go.com/Politics/transcript-abc-news-anchor-david-muir-interviews-president/story?id=45047602', 'http://abcnews.go.com/Politics/transcript-abc-news-anchor-david-muir-interviews-president/story?id=45047602', '2017-02-13 14:20:48', 'Politics'),
('TRANSCRIPT: ABC News Anchor David Muir Speaks With President Trump', 'This is a second transcript of ABC News anchor David Muirâ€™s interview with President Trump on Jan. 25, 2017, as they walked the White House grounds.', 'http://abcnews.go.com/Politics/transcript-abc-news-anchor-david-muir-speaks-president/story?id=45096081', 'http://abcnews.go.com/Politics/transcript-abc-news-anchor-david-muir-speaks-president/story?id=45096081', '2017-01-28 12:14:03', 'Politics'),
('Trump adviser Omarosa Manigault resigning, White House says', 'Manigault, a high-profile member of Trump\'s team, resigned Tuesday.', 'http://abcnews.go.com/Politics/trump-adviser-omarosa-manigault-resigning-post-white-house/story?id=51766259', 'http://abcnews.go.com/Politics/trump-adviser-omarosa-manigault-resigning-post-white-house/story?id=51766259', '2017-12-14 19:10:20', 'Politics'),
('Amtrak train was traveling 80 mph in 30-mph zone before derailing, NTSB says', 'The NTSB said overnight Tuesday the train was going 80 mph through a curve.', 'http://abcnews.go.com/US/amtrak-train-speed-limit-derailed-washington-state-ntsb/story?id=51878888', 'http://abcnews.go.com/US/amtrak-train-speed-limit-derailed-washington-state-ntsb/story?id=51878888', '2017-12-19 12:43:49', 'US'),
('Coldest air of season grips Northeast with bitter wind chills', 'The Northeast is expecting single-digit wind chills on Wednesday.', 'http://abcnews.go.com/US/coldest-air-season-grips-northeast-bitter-wind-chills/story?id=51760867', 'http://abcnews.go.com/US/coldest-air-season-grips-northeast-bitter-wind-chills/story?id=51760867', '2017-12-13 13:57:39', 'US'),
('Las Vegas massacre survivor leaves hospital: \'I still got a lot of living to do\'', 'A survivor of the Las Vegas music festival shooting expresses thanks to his girlfriend for saving his life and says they\'re both ready for the next chapter.', 'http://abcnews.go.com/US/las-vegas-massacre-survivor-leaves-hospital-lot-living/story?id=51768702', 'http://abcnews.go.com/US/las-vegas-massacre-survivor-leaves-hospital-lot-living/story?id=51768702', '2017-12-14 02:32:43', 'US'),
('Passenger says \'everything was in slow motion\' as Amtrak train derailed', 'A passenger on the Amtrak train that derailed near Tacoma, Washington, said \"everything was in slow motion\" as the accident happened.', 'http://abcnews.go.com/US/passenger-derailed-amtrak-train-slow-motion/story?id=51871562', 'http://abcnews.go.com/US/passenger-derailed-amtrak-train-slow-motion/story?id=51871562', '2017-12-19 03:29:30', 'US'),
('Inside the wrecked Amtrak train that derailed', 'Three were killed in the derailment near Dupont, Washington.', 'http://abcnews.go.com/US/photos-inside-wrecked-amtrak-train-deadly-washington-state/story?id=51882222', 'http://abcnews.go.com/US/photos-inside-wrecked-amtrak-train-deadly-washington-state/story?id=51882222', '2017-12-19 17:06:25', 'US'),
('WATCH:  Blind triplets credit their father with helping them earn highest rank in Boy Scouts', 'Nick, Leo and Steven Cantos thanked father Ollie Cantos for his encouragement.', 'http://abcnews.go.com/WNT/video/blind-triplets-credit-father-helping-earn-highest-rank-51523166', 'http://abcnews.go.com/WNT/video/blind-triplets-credit-father-helping-earn-highest-rank-51523166', '2017-12-04 16:59:46', 'WNT'),
('WATCH:  2 mariners rescued after being adrift in the Pacific for 5 months', 'The two women and their dogs were rescued by the Navy after being spotted 900 miles off the coast of Japan.', 'http://abcnews.go.com/WNT/video/mariners-rescued-adrift-pacific-months-50771893', 'http://abcnews.go.com/WNT/video/mariners-rescued-adrift-pacific-months-50771893', '2017-10-28 00:22:51', 'WNT'),
('WATCH:  World News 12/09/17: Students Lend Helping Hand to Beloved Bus Driver', 'Tensions build between Trump, civil rights activist John Lewis; Potential hazards of Christmas light decorations', 'http://abcnews.go.com/WNT/video/weekend-world-news-120917-students-lend-helping-hand-51694807', 'http://abcnews.go.com/WNT/video/weekend-world-news-120917-students-lend-helping-hand-51694807', '2017-12-12 17:58:19', 'WNT'),
('WATCH:  Weekend World News 12/17/17: Volunteer Football Coach Receives New Car as Thank-You for His Service', 'Blackout at Atlanta airport leaves thousands stranded; Officials warn against \'porch pirates\' during holiday season', 'http://abcnews.go.com/WNT/video/weekend-world-news-121717-volunteer-football-coach-receives-51852040', 'http://abcnews.go.com/WNT/video/weekend-world-news-121717-volunteer-football-coach-receives-51852040', '2017-12-18 03:47:38', 'WNT'),
('WATCH:  World News 12/04/17: Families With the Best Christmas Light Displays', 'Trump\'s new tax plan would provide top 1% with 62% of tax benefit; Parents settle lawsuit with dentist over death of their daughter', 'http://abcnews.go.com/WNT/video/world-news-120417-families-best-christmas-light-displays-51578134', 'http://abcnews.go.com/WNT/video/world-news-120417-families-best-christmas-light-displays-51578134', '2017-12-05 04:36:40', 'WNT'),
('WATCH:  World News 12/05/17: Russia Barred from Participating in the 2018 Winter Olympics', 'California governor declares a state of emergency due to wildfires in Ventura County; Body camera captures Georgia cop saving infant in distress', 'http://abcnews.go.com/WNT/video/world-news-120517-russia-barred-participating-2018-winter-51603510', 'http://abcnews.go.com/WNT/video/world-news-120517-russia-barred-participating-2018-winter-51603510', '2017-12-06 04:32:46', 'WNT'),
('WATCH:  World News 12/06/17: Trump Recognizes Jerusalem as the Capital of Israel and Plans to Move US Embassy from Tel Aviv', 'At least 38 senators call on Al Franken to resign; 4 major fires continue to burn and endanger residents in California', 'http://abcnews.go.com/WNT/video/world-news-120617-trump-recognizes-jerusalem-capital-israel-51634433', 'http://abcnews.go.com/WNT/video/world-news-120617-trump-recognizes-jerusalem-capital-israel-51634433', '2017-12-07 04:13:32', 'WNT'),
('WATCH:  World News 12/07/17: Sen. Al Franken to Resign from Senate Amid Sexual Misconduct Allegations', 'Ex-cop sentenced for shooting death of Walter Scott, People scrambling to escape the flames but not their humanity', 'http://abcnews.go.com/WNT/video/world-news-120717-sen-al-franken-resign-senate-51659384', 'http://abcnews.go.com/WNT/video/world-news-120717-sen-al-franken-resign-senate-51659384', '2017-12-08 19:57:40', 'WNT'),
('WATCH:  World News 12/08/17: First Responders Work Around the Clock Saving Lives', 'Misconduct crisis grows on Capitol Hill; FBI interviewed 21-year-old gunman back in 2016', 'http://abcnews.go.com/WNT/video/world-news-120817-responders-work-clock-saving-lives-51683747', 'http://abcnews.go.com/WNT/video/world-news-120817-responders-work-clock-saving-lives-51683747', '2017-12-09 04:45:48', 'WNT'),
('WATCH:  World News 12/10/17: California\'s Thomas Fire Intensifying', 'Moore denies allegations in new TV interview; 8-year-old New Jersey boy in spirit of giving back to Puerto Rico', 'http://abcnews.go.com/WNT/video/world-news-121017-californias-thomas-fire-intensifying-51709497', 'http://abcnews.go.com/WNT/video/world-news-121017-californias-thomas-fire-intensifying-51709497', '2017-12-11 03:17:42', 'WNT'),
('WATCH:  World News 12/11/17: New York City on Heightened Alert after ISIS-Inspired Attack', 'Women accusing Trump of sexual misconduct urge Congress to investigate; Detroit police hunt for gunman taking aim along Michigan highways', 'http://abcnews.go.com/WNT/video/world-news-121117-york-city-heightened-alert-isis-51730539', 'http://abcnews.go.com/WNT/video/world-news-121117-york-city-heightened-alert-isis-51730539', '2017-12-12 05:03:37', 'WNT'),
('WATCH:  World News 12/12/17: 6 Democratic Senators Call on Trump to Resign Over Sexual Misconduct Claims', 'Alabama voters head to polls for divisive Senate race; Authorities reveal more details on NYC subway bomber Akayed Ullah', 'http://abcnews.go.com/WNT/video/world-news-121217-democratic-senators-call-trump-resign-51754679', 'http://abcnews.go.com/WNT/video/world-news-121217-democratic-senators-call-trump-resign-51754679', '2017-12-13 10:05:53', 'WNT'),
('WATCH:  World News 12/13/17: Trump Responds After Doug Jones Wins Alabama Senate Race', '11-year-old girl wrongfully handcuffed by police in front of mother and aunt; Las Vegas shooting victim paralyzed after protecting girlfriend', 'http://abcnews.go.com/WNT/video/world-news-121317-trump-responds-doug-jones-wins-51780237', 'http://abcnews.go.com/WNT/video/world-news-121317-trump-responds-doug-jones-wins-51780237', '2017-12-14 04:39:23', 'WNT'),
('WATCH:  World News 12/14/17: Omarosa Manigault Talks About Her Resignation', 'Americans across the country share their holiday baking traditions; Disney makes $52.4 billion deal to expand its universe', 'http://abcnews.go.com/WNT/video/world-news-121417-omarosa-manigault-talks-resignation-51803280', 'http://abcnews.go.com/WNT/video/world-news-121417-omarosa-manigault-talks-resignation-51803280', '2017-12-15 04:10:45', 'WNT'),
('WATCH:  World News 12/15/17: More Than Half a Dozen Women Accuse Dustin Hoffman of Sexual Harassment', 'Soldier returns and surprises his daughter at daycare; Federal judge nominee Matthew Peterson struggles under questioning', 'http://abcnews.go.com/WNT/video/world-news-121517-half-dozen-women-accuse-dustin-51827022', 'http://abcnews.go.com/WNT/video/world-news-121517-half-dozen-women-accuse-dustin-51827022', '2017-12-16 03:44:21', 'WNT'),
('WATCH:  World News 12/18/17: Passenger on Derailed Train Said He Curled Into a Ball Praying for the Train to Come to a Stop', 'Congress set to vote tomorrow on Trump\'s tax bill; Americans share their best Christmas gift ideas', 'http://abcnews.go.com/WNT/video/world-news-121817-passenger-derailed-train-curled-ball-51874338', 'http://abcnews.go.com/WNT/video/world-news-121817-passenger-derailed-train-curled-ball-51874338', '2017-12-19 04:22:01', 'WNT'),
('David Muir on reporting to a \'divided America\' to Jimmy Kimmel', 'Muir discusses the presidential election and why all voices should be heard.', 'http://abcnews.go.com/WNT/WNT/world-news-tonights-david-muir-jimmy-kimmel-live/story?id=45550187', 'http://abcnews.go.com/WNT/WNT/world-news-tonights-david-muir-jimmy-kimmel-live/story?id=45550187', '2017-03-09 21:38:37', 'WNT'),
('Apple Music\'s next exclusives come from Noel Gallagher and Sam Smith', 'Apple isn&#039;t slowing down on exclusives any time soon.  It&#039;s releasing Apple Music-only concert films from two British superstars, Noel Gallagher and Sam Smith.  Gallagher&#039;s Who Built the Moon Live recaptures an early November gig at London&#039;s York Hal...', 'https://www.engadget.com/2017/12/15/apple-music-video-exclusives-from-noel-gallagher-sam-smith/', 'https://www.engadget.com/2017/12/15/apple-music-video-exclusives-from-noel-gallagher-sam-smith/', '2017-12-15 20:59:00', 'apple, applemusic, concert, entertainment, gear, internet, noelgallagher, samsmith, services, streaming, video'),
('Apple signs â€˜Battlestar Galacticaâ€™ developer for new space drama', 'Apple has ordered yet another TV series to add to its growing list of star-backed original productions. The company signed network sci-fi luminary Ronald D. Moore, veteran of several Star Trek series and developer of the Battlestar Galactica reboot,...', 'https://www.engadget.com/2017/12/15/apple-signs-battlestar-galactica-developer-for-new-space-drama/', 'https://www.engadget.com/2017/12/15/apple-signs-battlestar-galactica-developer-for-new-space-drama/', '2017-12-15 19:12:00', 'apple, av, battlestargalactica, entertainment, scifi, services, television'),
('As online ads fail, sites mine cryptocurrency', 'Between the incessant headlines and chatter on social media, it feels like everywhere we go some libertarian evangelist appears asking us if we have a second to talk about the blockchain -- like a religious wingnut lurking outside the grocery store.', 'https://www.engadget.com/2017/12/15/as-online-ads-fail-sites-mine-cryptocurrency/', 'https://www.engadget.com/2017/12/15/as-online-ads-fail-sites-mine-cryptocurrency/', '2017-12-15 20:00:00', 'badpassword, bitcoin, blockchain, coinhive, cryptocurrency, editorial, gear, mining, monero, opinion, security, starbucks'),
('BlackBerry will shutter its app store on December 31st, 2019', 'While there&#039;s little doubt that BlackBerry&#039;s in-house mobile platforms are finished (the last BB10 device shipped over 2 years ago), it&#039;s now giving holdouts some not-so-subtle hints that it&#039;s time to move on. The company has announced that it&#039;s shut...', 'https://www.engadget.com/2017/12/15/blackberry-app-store-closes-in-2019/', 'https://www.engadget.com/2017/12/15/blackberry-app-store-closes-in-2019/', '2017-12-15 19:44:00', 'blackberry, blackberry10, blackberryos, blackberryplaybook, blackberrytravel, blackberryworld, gear, mobile, playbook, smartphone'),
('Eve V review: The wisdom of the crowd mostly pays off', 'If you&#039;ve never heard of Eve, I like to think of it as the OnePlus of computers: By ditching middlemen, this 11-person startup found a way to build and sell premium computers at a significant discount. The difference is, the people in charge didn&#039;t d...', 'https://www.engadget.com/2017/12/15/eve-v-review/', 'https://www.engadget.com/2017/12/15/eve-v-review/', '2017-12-15 19:30:00', 'convertible, eve, evev, gear, hybrid, laptop, pc, personal computing, personalcomputing, review, video, windows, windows10'),
('Facebook tests option to bypass profiles and only post to News Feed', 'Facebook appears to be testing different options for how users share posts. The Next Web&#039;s Matt Navarra tweeted tests of two new ways to post content that let you bypass posting to your profile.', 'https://www.engadget.com/2017/12/15/facebook-bypass-profiles-post-to-news-feed/', 'https://www.engadget.com/2017/12/15/facebook-bypass-profiles-post-to-news-feed/', '2017-12-15 18:51:00', 'av, facebook, facebookprofile, gear, internet, mobile, mute, newsfeed'),
('Facebook tackles the question of whether social media is bad for us', 'As part of its &quot;Hard Questions&quot; series, Facebook took on the question of whether social media is good or bad for us. Citing a handful of academic studies, some done by Facebook researchers, Facebook Director of Research David Ginsberg and research sc...', 'https://www.engadget.com/2017/12/15/facebook-tackles-whether-social-media-is-bad/', 'https://www.engadget.com/2017/12/15/facebook-tackles-whether-social-media-is-bad/', '2017-12-15 20:41:00', 'av, facebook, gear, internet, markzuckerberg, mentalhealth, mobile, psychology, research, seanparker, socialmedia, socialnetwork, video'),
('Google Chrome beta delivers mute tool for autoplay videos', 'Months ago, a blog post by the good developers of Chrome let its users know that come January, users would be free of audio from autoplaying videos. As far as we know, those upgrades is still on track to arrive in early 2018 for all users, but you ca...', 'https://www.engadget.com/2017/12/15/google-chrome-64-beta-delivers-mute-autoplay-video-muting/', 'https://www.engadget.com/2017/12/15/google-chrome-64-beta-delivers-mute-autoplay-video-muting/', '2017-12-15 22:01:00', 'autoplay, chrome, chromebeta, google, internet'),
('Google ends Tango support to fully focus on ARCore', 'Google began delving into the world of AR with its 2014 venture Project Tango, or just Tango as of last year, and its AR work has grown quite a bit since then. Earlier this year, it unveiled ARCore, an augmented reality platform that differs from Tan...', 'https://www.engadget.com/2017/12/15/google-ends-tango-support-focus-arcore/', 'https://www.engadget.com/2017/12/15/google-ends-tango-support-focus-arcore/', '2017-12-15 22:16:00', 'ar, arcore, arstickers, av, gear, google, mobile, pixel2, projecttango'),
('Google Inbox will remind you to unsubscribe from unread promo emails', 'Google has made email a much less tedious, junky affair for a lot of us, and it&#039;s about to take another step to helping us clean out our inboxes. According to a report over at Android Police, users of Google&#039;s Inbox app will start seeing new tips tha...', 'https://www.engadget.com/2017/12/15/google-inbox-remind-unsubscribe-unread-promo-email/', 'https://www.engadget.com/2017/12/15/google-inbox-remind-unsubscribe-unread-promo-email/', '2017-12-15 23:56:00', 'android, app, gear, google, inbox, internet, mobile, unsubscribe, web'),
('Google Maps will now tell you when to get off the bus or train', 'A mass transit feature for the Android version of Google Maps that notifies you when you need to get off the bus is finally live. It also includes step-by-step navigation, departure times and ETAs for your next public transportation ride. You can als...', 'https://www.engadget.com/2017/12/15/google-maps-will-tell-when-to-get-off-bus-train/', 'https://www.engadget.com/2017/12/15/google-maps-will-tell-when-to-get-off-bus-train/', '2017-12-15 21:20:00', 'gear, google, googlemaps, maps, masstransit, mobile, navigation, publictransportation, stepbystep, transit'),
('iTunes isn\'t coming to the Windows Store this year after all', 'iTunes for Windows users are going to be disappointed. Despite the promises of both Apple and Microsoft to bring the popular music and app software to the Microsoft Store this year, it appears as if we&#039;ll all have to wait a little longer.', 'https://www.engadget.com/2017/12/15/itunes-for-windows-store-delayed/', 'https://www.engadget.com/2017/12/15/itunes-for-windows-store-delayed/', '2017-12-15 21:41:00', 'apple, gear, itunes, microsoft, microsoftstore, personal computing, personalcomputing'),
('\'Jacobs letter\' unsealed, accuses Uber of spying, hacking', 'Waymo&#039;s lawsuit against Uber for allegedly stealing technology for self-driving cars hasn&#039;t gone to trial yet, because the judge received a letter from the Department of Justice suggesting Uber withheld crucial evidence. That letter, with some redact...', 'https://www.engadget.com/2017/12/15/jacobs-letter-unsealed-accuses-uber-of-spying-hacking/', 'https://www.engadget.com/2017/12/15/jacobs-letter-unsealed-accuses-uber-of-spying-hacking/', '2017-12-16 02:33:00', 'alphabet, anthonylevandowski, business, gear, judgealsup, otto, richardjacobs, self-drivingcar, ssg, tradesecrets, transportation, uber, waymo'),
('\'L.A. Noire: The VR Case Files\' is available now for HTC Vive', 'We were excited to hear that 2011 detective simulator L.A. Noire was headed to modern consoles and the HTC Vive for some VR action. The title received some visual upgrades, too, making the jump to PS4, Xbox One and the Switch a bit more graphically a...', 'https://www.engadget.com/2017/12/15/l-a-noire-the-vr-case-files-available-for-htc-vive/', 'https://www.engadget.com/2017/12/15/l-a-noire-the-vr-case-files-available-for-htc-vive/', '2017-12-16 01:27:00', 'av, gaming, htc, htcvive, lanoire, lanoirevr, rockstar, rockstargames, steam, video, vr'),
('\'PUBG\' tests a replay feature as it creeps toward v1.0', 'Now that PlayerUnknown&#039;s Battlegrounds has launched in Early Access on Xbox One, its next milestone is an official retail release out of beta on the PC. That&#039;s expected to happen next week, but players who can&#039;t wait have a few new tweaks to try out...', 'https://www.engadget.com/2017/12/15/pubg-tests-a-replay-feature-as-it-creeps-toward-v1-0/', 'https://www.engadget.com/2017/12/15/pubg-tests-a-replay-feature-as-it-creeps-toward-v1-0/', '2017-12-16 04:58:00', 'av, gaming, map, personal computing, personalcomputing, playerunknownsbattlegrounds, pubg, replay, steam, video'),
('Set sail with your pals in a new â€˜Adventure Timeâ€™ game', 'A new Adventure Time game is in the works and it features some maritime fun, a nameable boat and pirates. Adventure Time: Pirates of the Enchiridion begins with a flooded Land of Ooo and Adventure Time characters have to set off to figure out what&#039;s...', 'https://www.engadget.com/2017/12/15/set-sea-new-adventure-time-game/', 'https://www.engadget.com/2017/12/15/set-sea-new-adventure-time-game/', '2017-12-15 22:47:00', 'adventuretime, adventuretime:piratesoftheenchiridion, av, gaming, microsoft, nintendo, nintendo3ds, nintendoswitch, outrightgames, playstation4, sony, xboxone'),
('Researchers use sperm to deliver cancer drugs to tumors', 'Chemotherapy has a lot of terrible side effects and that&#039;s partly because the drugs being used to fight cancer also attack healthy cells. Figuring out a way to deliver drugs to tumors without affecting healthy tissue is a challenge and a problem that...', 'https://www.engadget.com/2017/12/15/sperm-deliver-cancer-drugs-tumors/', 'https://www.engadget.com/2017/12/15/sperm-deliver-cancer-drugs-tumors/', '2017-12-16 03:42:00', 'cancer, chemotherapy, drugdelivery, gear, medicine, research, sperm, tomorrow, tumor, video'),
('Buy an Xbox One X and get \'PUBG\' free for a limited time', 'From December 17th through the 31st, Microsoft will give everyone who purchases an Xbox One X a copy of PlayerUnknown&#039;s Battlegrounds. A post on Xbox Wire says that over a million people played the battle royale game within 48 hours of being availabl...', 'https://www.engadget.com/2017/12/15/xbox-one-x-free-pubg-promo/', 'https://www.engadget.com/2017/12/15/xbox-one-x-free-pubg-promo/', '2017-12-15 20:19:00', 'business, gaming, microsoft, playerunknownsbattlegrounds, promo, pubg, xbox, xboxone, xboxonex'),
('California advises against keeping your phone in your pocket', 'The jury is still out on whether or not cellphone radiation is bad for you, but California&#039;s Department of Public Health isn&#039;t taking any chances.  The agency just issued an advisory that suggests residents should take steps to limit their exposure t...', 'https://www.engadget.com/2017/12/16/california-advises-against-keeping-your-phone-in-your-pocket/', 'https://www.engadget.com/2017/12/16/california-advises-against-keeping-your-phone-in-your-pocket/', '2017-12-16 19:02:00', 'california, californiadepartmentofpublichhealth, cdph, cellphone, gear, health, medicine, mobile, radiation, safety, smartphone'),
('CDC barred from using \'science-based\' in budget documents', 'We can just imagine CDC personnel still shaking their heads after finding out that they can&#039;t use certain terms in official documents for next year&#039;s budget. According to The Washington Post, the Trump administration has prohibited the CDC from using...', 'https://www.engadget.com/2017/12/16/cdc-banned-words-evidence-science/', 'https://www.engadget.com/2017/12/16/cdc-banned-words-evidence-science/', '2017-12-16 22:06:00', 'bannedwords, cdc, gear, politics'),
('Firefox faces backlash for auto-installing \'Mr. Robot\' add-on', 'A curious add-on called &quot;Looking Glass&quot; started popping up on Firefox for a number of users this past week -- even if they didn&#039;t give the browser permission to install it. Due to its nebulous nature and creepy description that only said &quot;MY REALITY...', 'https://www.engadget.com/2017/12/16/firefox-mr-robot-extension/', 'https://www.engadget.com/2017/12/16/firefox-mr-robot-extension/', '2017-12-16 17:35:00', 'entertainment, firefox, mozilla, mrrobot, security, tvshow'),
('Google won\'t show news from sites that hide their country of origin', 'Google&#039;s ongoing quest to curb fake news now includes sites that are less than honest about their home turf.  The company has updated its Google News guidelines to forbid sites that &quot;misrepresent or conceal their country of origin&quot; or otherwise are a...', 'https://www.engadget.com/2017/12/16/google-bans-news-sites-which-hide-country-of-origin/', 'https://www.engadget.com/2017/12/16/google-bans-news-sites-which-hide-country-of-origin/', '2017-12-16 20:33:00', 'fakenews, gear, google, googlenews, internet, news, russia, search, web'),
('Netflix may run Watergate series developed by George Clooney', 'Netflix&#039;s ability to reel in big-name stars may have just secured a very topical political drama. Sources for Hollywood Reporter and Variety have learned that George Clooney and Bridge of Spies writer Matt Charman are working on Watergate, an eight-e...', 'https://www.engadget.com/2017/12/16/netflix-may-run-watergate-series-developed-by-george-clooney/', 'https://www.engadget.com/2017/12/16/netflix-may-run-watergate-series-developed-by-george-clooney/', '2017-12-16 16:06:00', 'entertainment, georgeclooney, internet, netflix, richardnixon, services, streaming, television, tv, watergate'),
('The Morning After: Weekend Edition', 'Hey, good morning! You look fabulous.\n\nWelcome to the weekend. If you&#039;re still holiday shopping (or haven&#039;t started yet), then this might be a good time to mention that Amazon extended its free shipping before Christmas deadline through today. Now, f...', 'https://www.engadget.com/2017/12/16/the-morning-after-weekend-edition/', 'https://www.engadget.com/2017/12/16/the-morning-after-weekend-edition/', '2017-12-16 13:00:00', 'entertainment, food and drink, gadgetry, gadgets, gaming, gear, themorningafter'),
('Uber Eats offers insurance for its European couriers', 'Uber Eats only just turned two years old, but like other &quot;gig economy&quot; businesses, it&#039;s facing scrutiny over how it classifies workers. In Europe, the company is partnering with Axa to offer couriers an insurance package that covers accidents, hospit...', 'https://www.engadget.com/2017/12/16/uber-eats-offers-insurance-for-its-european-couriers/', 'https://www.engadget.com/2017/12/16/uber-eats-offers-insurance-for-its-european-couriers/', '2017-12-16 09:57:00', 'business, eu, europe, gear, gigeconomy, insurance, uber, ubereats, uk'),
('Adidas closes its digital sports division', 'Sportswear brands might be reviving their interest in fitness technology, but Adidas is staging its comeback in a very roundabout way.  The company&#039;s American segment is closing its dedicated digital sports division and folding the group&#039;s work into...', 'https://www.engadget.com/2017/12/18/adidas-closes-digital-sports-division/', 'https://www.engadget.com/2017/12/18/adidas-closes-digital-sports-division/', '2017-12-19 04:37:00', 'adidas, fitbit, fitness, gear, ionic, runtastic, sports, wearable, wearables'),
('China will allow self-driving car tests on public roads', 'China is opening up its roads to self-driving cars. The Beijing Municipal Transport Commission released a statement today saying that on certain roads and under certain conditions, companies registered in China will be able to test their autonomous v...', 'https://www.engadget.com/2017/12/18/china-self-driving-car-tests-public-roads/', 'https://www.engadget.com/2017/12/18/china-self-driving-car-tests-public-roads/', '2017-12-19 03:22:00', 'autonomousvehicles, baidu, china, driverless, gear, self-drivingcar, transportation'),
('US government names North Korea as the source of WannaCry', 'Donald Trump&#039;s homeland security adviser, Tom Bossert, said in a Wall Street Journal op-ed that &quot;after careful investigation, the U.S. today publicly attributes the massive &quot;WannaCry&quot; cyberattack to North Korea.&quot; Coming during increasing tensions bet...', 'https://www.engadget.com/2017/12/18/north-korea-wannacry/', 'https://www.engadget.com/2017/12/18/north-korea-wannacry/', '2017-12-19 04:57:00', 'attribution, cyberattack, dprk, gear, northkorea, politics, ransomware, security, trumpadminsitration, wannacry, wannacrypt'),
('What\'s on TV: \'Bright,\' \'Christopher Nolan 4K Collection\'', 'As the clock ticks down on 2017, we&#039;re finally checking out Netflix&#039;s $90 million+ movie. Bright stars Will Smith as a cop in a world full of orcs and other mystical creatures, and we&#039;ll see if it&#039;s enough to pull attention away from flicks currently...', 'https://www.engadget.com/2017/12/18/whats-on-tv-bright-christopher-nolan-4k-collection/', 'https://www.engadget.com/2017/12/18/whats-on-tv-bright-christopher-nolan-4k-collection/', '2017-12-19 02:28:00', 'av, bright, entertainment, gaming, listings, mustseehdtv, pubg, video'),
('Alamo Drafthouse to open video rental store with rare VHS tapes', 'Do you miss the days when finding a movie to watch meant browsing the local video store, hoping that you&#039;d stumble across some rare gem?  Alamo Drafthouse sure does.  After amassing collections from small shops, the enthusiast-driven theater chain is...', 'https://www.engadget.com/2017/12/19/alamo-drafthouse-video-rental-store-with-vhs/', 'https://www.engadget.com/2017/12/19/alamo-drafthouse-video-rental-store-with-vhs/', '2017-12-19 06:59:00', 'alamodrafthouse, av, blu-ray, dvd, entertainment, gear, rentals, vhs, videorental'),
('Echo Look can give you style tips from Amazon\'s fashionistas', 'If you&#039;re tiring of the Echo Look&#039;s AI-powered style tips, we have good news. Now, you can submit your full-body selfies to the Amazon Spark hive for feedback from real-life humans. The e-retail giant launched the camera-equipped Echo Look in June as...', 'https://www.engadget.com/2017/12/19/amazon-echo-look-spark-style-tips/', 'https://www.engadget.com/2017/12/19/amazon-echo-look-spark-style-tips/', '2017-12-19 13:01:00', 'amazon, amazonspark, echolook, gadgetry, gadgets, gear, mobile'),
('Geeks are using science to make the best chocolate ever', 'Rob Anderson is a geek. So he makes chocolate for other geeks, or, more accurately, &quot;people who really like chocolate and geek out about it.&quot;\n\nWhat does he mean by that? If you change one step of the chocolate-making process, you change the taste of...', 'https://www.engadget.com/2017/12/19/bean-to-bar-chocolate-tech/', 'https://www.engadget.com/2017/12/19/bean-to-bar-chocolate-tech/', '2017-12-19 15:30:00', 'beantobar, business, chocolate, cocoa, dandelion, entertainment, food and drink, food-and-drink, foodanddrink, foodtech, gear, winnower'),
('Caavoâ€™s voice-enabled universal remote ships February 14th', 'The Caavo universal TV control system, which is aimed at simplifying home TV setups through machine vision, is set to ship on February 14th, The Verge reports. Initially planned to ship last June, the $399 system boasts the ability to control and nav...', 'https://www.engadget.com/2017/12/19/caavo-universal-remote-ships-february-14th/', 'https://www.engadget.com/2017/12/19/caavo-universal-remote-ships-february-14th/', '2017-12-19 17:21:00', 'av, caavo, gadgetry, gadgets, gear, home, machinevision, tv, universalremote'),
('\'Dragon Quest Builders\' arrives on Switch in February', 'Square Enix&#039;s Minecraft&amp;shy;-style construction game Dragon Quest Builders is coming to Nintendo Switch on February 9 next year. The game -- which was released last year on PS4, PS3 and Vita -- sees players gather materials, reconstruct towns and fig...', 'https://www.engadget.com/2017/12/19/dragon-quest-builders-arrives-on-switch-in-february/', 'https://www.engadget.com/2017/12/19/dragon-quest-builders-arrives-on-switch-in-february/', '2017-12-19 14:19:00', 'av, dragonquestbuilders, game, gaming, minecraft, nintendo, squareenix, switch'),
('Engadget giveaway: Win an Anki Cozmo robot and Overdrive racing set!', 'When the holiday season rolls around, it&#039;s always a good excuse to get in a little play time. Picking up a few items for yourself or guaranteeing second-hand fun after you gift them is a win-win scenario. This week, smart-gadget maker Anki has passed...', 'https://www.engadget.com/2017/12/19/engadget-giveaway-win-an-anki-cozmo-robot-and-overdrive-racing/', 'https://www.engadget.com/2017/12/19/engadget-giveaway-win-an-anki-cozmo-robot-and-overdrive-racing/', '2017-12-19 16:00:00', 'anki, ankioverdrive, contest, cozmo, cozmocollectorsedition, fast, &, furious, gadgetry, gadgets, games, gear, home, mobile, racingcar, robots, toys'),
('FAA names seven nuclear research labs as no-drone zones', 'The FAA has granted DOE&#039;s request to make seven of its facilities no-drone zones -- and they&#039;re all nuclear research laboratories. Starting on December 29th, you can no longer fly your UAVs within 400 feet of Hanford Site in Franklin County Washingto...', 'https://www.engadget.com/2017/12/19/faa-nuclear-research-labs-no-drone-zone/', 'https://www.engadget.com/2017/12/19/faa-nuclear-research-labs-no-drone-zone/', '2017-12-19 12:02:00', 'departmentofenergy, drone, faa, gadgetry, gadgets, gear, nuclearresearchlabs, restriction'),
('Facebook will alert you when someone posts your photo, tagged or not', 'Facebook has launched new tools powered by its facial recognition tech -- the same one that suggests friends to tag in photos. To start with, it has beefed up the alternative text feature it rolled out last year, which describes a photo&#039;s contents fo...', 'https://www.engadget.com/2017/12/19/facebook-facial-recognition-tools/', 'https://www.engadget.com/2017/12/19/facebook-facial-recognition-tools/', '2017-12-19 16:18:00', 'accessibility, facebook, gear, internet, socialmedia, socialnetwork'),
('Facebook brings its social VR \'Spaces\' to the HTC Vive', 'Earlier this year, Facebook unveiled Spaces, its inaugural attempt at bringing the social network to VR. And, seeing as Facebook also owns Oculus, it&#039;s no surprise that Spaces was a Rift-exclusive at launch. But, just as Facebook is on every platform...', 'https://www.engadget.com/2017/12/19/facebook-spaces-vive/', 'https://www.engadget.com/2017/12/19/facebook-spaces-vive/', '2017-12-19 17:00:00', 'av, facebook, facebookspaces, gear, htc, htcvive, internet, oculus, personal computing, personalcomputing, rift, socialvr, spaces, virtualreality, vive, vr'),
('France gives WhatsApp a month to stop sharing data with Facebook', 'After the EU slapped it with a &amp;euro;110 million fine over unlawful WhatsApp data sharing, you&#039;d think Facebook would be eager to comply with local privacy laws. But France says it has not cooperated with data protection authority CNIL, and could fac...', 'https://www.engadget.com/2017/12/19/france-whatsapp-facebook-data-privacy/', 'https://www.engadget.com/2017/12/19/france-whatsapp-facebook-data-privacy/', '2017-12-19 13:31:00', 'cnil, consent, eu, facebook, france, gear, internet, privacy, whatsapp'),
('Google Home Max review: An assistant for music lovers', 'Smart speakers like the Amazon Echo and Google Home have proved useful -- but they tend not to sound very good. Sure, they&#039;re serviceable in a pinch, and are better than most cheap Bluetooth speakers, but they don&#039;t compare to options like the entire...', 'https://www.engadget.com/2017/12/19/google-home-max-review/', 'https://www.engadget.com/2017/12/19/google-home-max-review/', '2017-12-19 14:00:00', 'av, entertainment, gear, google, googleassistant, googlehome, googlehomemax, home, homemax, review'),
('London police will use AI to look for child porn on seized devices', 'Around this time last year, Interpol revealed it was using an AI system to track down child porn on P2P networks in the global hunt for predators. Tech firms like Google and Microsoft have been using their own tools in the fight against child exploit...', 'https://www.engadget.com/2017/12/19/london-police-ai-child-abuse-images/', 'https://www.engadget.com/2017/12/19/london-police-ai-child-abuse-images/', '2017-12-19 16:13:00', 'ai, artificialintelligence, crime, met, metropolitanpolice, politics, tomorrow'),
('Microsoft improves transparency for sexual harassment claims', 'The slew of sexual harassment disclosures in the entertainment business has started to influence the technology world, and Microsoft in particular sees this as an opportunity to rethink its policies.  It&#039;s waiving the requirement for pre-dispute arbi...', 'https://www.engadget.com/2017/12/19/microsoft-ends-arbitration-for-sexual-harassment-claims/', 'https://www.engadget.com/2017/12/19/microsoft-ends-arbitration-for-sexual-harassment-claims/', '2017-12-19 15:46:00', 'arbitration, business, crime, gear, harassment, microsoft, sexualharassment'),
('NASA will take images of its quiet supersonic jet\'s shockwaves', 'When NASA begins testing its supersonic jet, you won&#039;t only hear about it -- you&#039;ll see cool images from the experiments, too. The agency has recently completed a series of flight tests proving that the imaging technique it developed is capable of ca...', 'https://www.engadget.com/2017/12/19/nasa-shockwave-images-quiet-supersonic-jet/', 'https://www.engadget.com/2017/12/19/nasa-shockwave-images-quiet-supersonic-jet/', '2017-12-19 15:16:00', 'gear, jet, lowboomflightdemonstrationaircraft, nasa, supersonic, transportation, x-plane'),
('Switching mobile operators could soon begin with a text', 'Ofcom has introduced new rules that should make it easier to switch mobile networks in the UK. At the moment, cancelling a contract and setting up a new one is complicated and time consuming, especially if you want to keep your old number. You have t...', 'https://www.engadget.com/2017/12/19/ofcom-auto-switch-mobile-phone-networks/', 'https://www.engadget.com/2017/12/19/ofcom-auto-switch-mobile-phone-networks/', '2017-12-19 13:09:00', 'business, carriers, gear, mobile, mobilenetworks, networks, ofcom, politics, sim, simcard'),
('Plexâ€™s incubator launches a Winamp-inspired music player', 'Plex&#039;s comprehensive media server, complete with live TV and all-round entertainment playback, is a big draw for cord cutters. But, it seems the company is itching to unleash even more products. To that end, it just unveiled Plex Labs, a new incubato...', 'https://www.engadget.com/2017/12/19/plex-labs-plexamp-music-player/', 'https://www.engadget.com/2017/12/19/plex-labs-plexamp-music-player/', '2017-12-19 08:02:00', 'av, gear, mediaserver, musicplayer, plex, plexamp, plexlabs, winamp'),
('Samsung\'s mega-wide gaming monitor is first to be HDR certified', 'Last week VESA (finally) launched an HDR standard for computer displays to tell consumers whether a pricey monitor will show games and movies the way the creators intended. Samsung has announced that it&#039;s 49-inch QLED super ultra-wide monitor, the CH...', 'https://www.engadget.com/2017/12/19/samsung-chg90-gaming-display-hdr-certified/', 'https://www.engadget.com/2017/12/19/samsung-chg90-gaming-display-hdr-certified/', '2017-12-19 14:38:00', '49-inch, av, chg90, displayhdr, entertainment, gaming, gear, personal computing, personalcomputing, qled, samsung'),
('The Morning After: Tuesday, December 19th 2017', 'Good morning! This morning we wait with bated breath for a phone screen that will heal itself, test out Amazon&#039;s adorable Echo Spot and kick off our year in review coverage.', 'https://www.engadget.com/2017/12/19/the-morning-after-tuesday-december-19th-2017/', 'https://www.engadget.com/2017/12/19/the-morning-after-tuesday-december-19th-2017/', '2017-12-19 11:00:00', 'entertainment, gaming, gear, internet, themorningafter'),
('This year we took small, important steps toward the Singularity', 'We won&#039;t have to wait until 2019 for our Blade Runner future, mostly because artificially intelligent robots already walk, roll and occasionally backflip among us. They&#039;re on our streets and in our stores. Some have wagged their way into our hearts w...', 'https://www.engadget.com/2017/12/19/this-year-we-took-small-important-steps-toward-the-singularity/', 'https://www.engadget.com/2017/12/19/this-year-we-took-small-important-steps-toward-the-singularity/', '2017-12-19 15:00:00', 'ai, alphago, amazon, armyresearchoffice, artificialintelligence, asimov, carnegiemellon, ethics, georgiainstituteoftechnology, google, manuelaveloso, military, moral, morality, robots, ronarkin, tomorrow, usarmy, war, yearinreview, yir2017'),
('UPS is Teslaâ€™s latest electric semi-truck customer', 'UPS has placed the largest Tesla semi-truck order to date, reserving 125 of the trucks. Since unveiling the electric vehicles last month, Tesla has received quite a few orders from major companies. PepsiCo has ordered 100, Anheuser-Busch ordered 40 a...', 'https://www.engadget.com/2017/12/19/ups-tesla-electric-semi-truck-customer/', 'https://www.engadget.com/2017/12/19/ups-tesla-electric-semi-truck-customer/', '2017-12-19 16:39:00', 'environment, ev, gear, green, tesla, teslasemi, transportation, ups'),
('Wink pairs with Sonos to auto-tune your smart home', 'Sonos announced it was opening up its ecosystem a couple months back and, sure enough, controls for Tidal and Pandora followed, with Airplay 2 support also inbound. Unsurprisingly, its upcoming Alexa integration hogged the limelight, but the smart sp...', 'https://www.engadget.com/2017/12/19/wink-sonos-smart-home-controls/', 'https://www.engadget.com/2017/12/19/wink-sonos-smart-home-controls/', '2017-12-19 09:32:00', 'gear, home, smarthome, smartspeaker, sonos, wink, winkhub2');
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
